window.AMARA_PRODUCTS = [
  {
    id: 1,
    slug: "saffron-bloom-tote",
    name: "Saffron Bloom Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 32,
    tag: "Best Seller",
    description: "A bright marigold hand-dyed tote with a playful, sunlit finish for everyday carry.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.50 (1).jpeg",
    purchasable: true,
  },
  {
    id: 2,
    slug: "sorbet-sky-tote",
    name: "Sorbet Sky Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 34,
    tag: "Fresh Drop",
    description: "A cotton tote washed in blue and rose tones with a soft resort-inspired mood.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.50.jpeg",
    purchasable: true,
  },
  {
    id: 3,
    slug: "coastal-duo-edit",
    name: "Coastal Duo Edit",
    category: "editorial",
    categoryLabel: "Styled Edit",
    price: 58,
    tag: "Gift Pair",
    description: "A peach-and-lime duo styled for vacation gifting, brunch edits, and light summer wardrobes.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.51 (1).jpeg",
    purchasable: true,
  },
  {
    id: 4,
    slug: "orchid-veil-tote",
    name: "Orchid Veil Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 36,
    tag: "Hand Dyed",
    description: "A lavender-and-rose tote with soft marbling and an elevated handcrafted feel.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.51 (2).jpeg",
    purchasable: true,
  },
  {
    id: 5,
    slug: "lavender-mist-tote",
    name: "Lavender Mist Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 35,
    tag: "Pastel Icon",
    description: "A dreamy blue-lilac tote finished with delicate fringe and a soft watercolor wash.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.51 (3).jpeg",
    purchasable: true,
  },
  {
    id: 6,
    slug: "azure-tide-tote",
    name: "Azure Tide Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 35,
    tag: "Cool Tone",
    description: "A crisp ice-blue tote with tie-dye texture and a clean, understated finish.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.51.jpeg",
    purchasable: true,
  },
  {
    id: 7,
    slug: "atelier-rainbow-rail",
    name: "Atelier Rainbow Rail",
    category: "editorial",
    categoryLabel: "Editorial Story",
    price: null,
    tag: "Lookbook",
    description: "An editorial group shot showing Amara's color story across the collection.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.52 (1).jpeg",
    purchasable: false,
  },
  {
    id: 8,
    slug: "sunbeam-pair-tote-set",
    name: "Sunbeam Pair Tote Set",
    category: "editorial",
    categoryLabel: "Styled Edit",
    price: 60,
    tag: "Duo Set",
    description: "A bright two-piece pairing in butter yellow, blue, and fuchsia for cheerful gifting.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.52 (2).jpeg",
    purchasable: true,
  },
  {
    id: 9,
    slug: "pastel-table-edit",
    name: "Pastel Table Edit",
    category: "editorial",
    categoryLabel: "Editorial Story",
    price: null,
    tag: "Lookbook",
    description: "A styled flatlay featuring Amara's hand-dyed tote palette and playful accessory pairing.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.52 (3).jpeg",
    purchasable: false,
  },
  {
    id: 10,
    slug: "peach-haze-tote",
    name: "Peach Haze Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 33,
    tag: "Soft Pastel",
    description: "A blush-and-blue tote with a breezy washed finish that feels light and easy.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.52.jpeg",
    purchasable: true,
  },
  {
    id: 11,
    slug: "garden-lineup-story",
    name: "Garden Lineup Story",
    category: "editorial",
    categoryLabel: "Editorial Story",
    price: null,
    tag: "Campaign",
    description: "A campaign image presenting the collection in a garden setting with playful color spacing.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.53 (1).jpeg",
    purchasable: false,
  },
  {
    id: 12,
    slug: "blue-lagoon-tote",
    name: "Blue Lagoon Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 35,
    tag: "Signature Blue",
    description: "A clear sky-blue tote with artisan marbling and fringe detail for a standout daily carry.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.53.jpeg",
    purchasable: true,
  },
];
