// Add new scarf products below using image paths from ./assets/scarves/.
// Example:
// {
//   id: 13,
//   slug: "rose-cloud-scarf",
//   name: "Rose Cloud Scarf",
//   category: "scarf",
//   categoryLabel: "Custom Scarf",
//   price: 449,
//   tag: "New Line",
//   description: "A lightweight hand-dyed scarf with soft pink and ivory transitions.",
//   image: "./assets/scarves/your-photo-file.jpg",
//   purchasable: true,
// },

window.AMARA_PRODUCTS = [
  {
    id: 1,
    slug: "saffron-bloom-tote",
    name: "Saffron Bloom Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 449,
    tag: "Best Seller",
    description: "A bright marigold hand-dyed tote with a playful, sunlit finish for everyday carry.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.50 (1).jpeg",
    purchasable: true,
  },
  {
    id: 2,
    slug: "sorbet-sky-tote",
    name: "Sorbet Sky Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 499,
    tag: "Fresh Drop",
    description: "A cotton tote washed in blue and rose tones with a soft resort-inspired mood.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.50.jpeg",
    purchasable: true,
  },
  {
    id: 3,
    slug: "coastal-duo-edit",
    name: "Coastal Duo Edit",
    category: "editorial",
    categoryLabel: "Styled Edit",
    price: 599,
    tag: "Gift Pair",
    description: "A peach-and-lime duo styled for vacation gifting, brunch edits, and light summer wardrobes.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.51 (1).jpeg",
    purchasable: true,
  },
  {
    id: 4,
    slug: "orchid-veil-tote",
    name: "Orchid Veil Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 549,
    tag: "Hand Dyed",
    description: "A lavender-and-rose tote with soft marbling and an elevated handcrafted feel.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.51 (2).jpeg",
    purchasable: true,
  },
  {
    id: 5,
    slug: "lavender-mist-tote",
    name: "Lavender Mist Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 529,
    tag: "Pastel Icon",
    description: "A dreamy blue-lilac tote finished with delicate fringe and a soft watercolor wash.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.51 (3).jpeg",
    purchasable: true,
  },
  {
    id: 6,
    slug: "azure-tide-tote",
    name: "Azure Tide Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 519,
    tag: "Cool Tone",
    description: "A crisp ice-blue tote with tie-dye texture and a clean, understated finish.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.51.jpeg",
    purchasable: true,
  },
  {
    id: 7,
    slug: "atelier-rainbow-rail",
    name: "Atelier Rainbow Rail",
    category: "editorial",
    categoryLabel: "Editorial Story",
    price: null,
    tag: "Lookbook",
    description: "An editorial group shot showing Amara's color story across the collection.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.52 (1).jpeg",
    purchasable: false,
  },
  {
    id: 8,
    slug: "sunbeam-pair-tote-set",
    name: "Sunbeam Pair Tote Set",
    category: "editorial",
    categoryLabel: "Styled Edit",
    price: 599,
    tag: "Duo Set",
    description: "A bright two-piece pairing in butter yellow, blue, and fuchsia for cheerful gifting.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.52 (2).jpeg",
    purchasable: true,
  },
  {
    id: 9,
    slug: "pastel-table-edit",
    name: "Pastel Table Edit",
    category: "editorial",
    categoryLabel: "Editorial Story",
    price: null,
    tag: "Lookbook",
    description: "A styled flatlay featuring Amara's hand-dyed tote palette and playful accessory pairing.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.52 (3).jpeg",
    purchasable: false,
  },
  {
    id: 10,
    slug: "peach-haze-tote",
    name: "Peach Haze Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 479,
    tag: "Soft Pastel",
    description: "A blush-and-blue tote with a breezy washed finish that feels light and easy.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.52.jpeg",
    purchasable: true,
  },
  {
    id: 11,
    slug: "garden-lineup-story",
    name: "Garden Lineup Story",
    category: "editorial",
    categoryLabel: "Editorial Story",
    price: null,
    tag: "Campaign",
    description: "A campaign image presenting the collection in a garden setting with playful color spacing.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.53 (1).jpeg",
    purchasable: false,
  },
  {
    id: 12,
    slug: "blue-lagoon-tote",
    name: "Blue Lagoon Tote",
    category: "tote",
    categoryLabel: "Signature Tote",
    price: 539,
    tag: "Signature Blue",
    description: "A clear sky-blue tote with artisan marbling and fringe detail for a standout daily carry.",
    image: "./assets/products/WhatsApp Image 2026-03-24 at 16.36.53.jpeg",
    purchasable: true,
  },
  {
    id: 13,
    slug: "rose-cloud-scarf",
    name: "Rose Cloud Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 349,
    tag: "New Line",
    description: "A lightweight scarf designed for soft drape, gifting, and easy personalized styling.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19.jpeg",
    purchasable: true,
    customizationRequired: false,
  },
  {
    id: 14,
    slug: "blush-sand-scarf",
    name: "Blush Sand Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 369,
    tag: "Soft Pastel",
    description: "A soft everyday scarf imagined for subtle color, custom names, and gift-ready styling.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19 (1).jpeg",
    purchasable: true,
    customizationRequired: false,
  },
  {
    id: 15,
    slug: "lilac-glow-scarf",
    name: "Lilac Glow Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 399,
    tag: "Hand Dyed",
    description: "A personalized scarf option with a boutique feel, made for festive edits and thoughtful gifting.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19 (2).jpeg",
    purchasable: true,
    customizationRequired: false,
  },
  {
    id: 16,
    slug: "sunwash-scarf",
    name: "Sunwash Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 379,
    tag: "Giftable",
    description: "A bright, easy scarf line that works beautifully on its own or paired with an Amara tote.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19 (3).jpeg",
    purchasable: true,
    customizationRequired: false,
  },
  {
    id: 17,
    slug: "ivory-bloom-scarf",
    name: "Ivory Bloom Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 429,
    tag: "Custom Ready",
    description: "A graceful scarf style for return gifts, bridesmaid sets, and light occasion dressing.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19 (4).jpeg",
    purchasable: true,
    customizationRequired: false,
  },
  {
    id: 18,
    slug: "petal-wave-scarf",
    name: "Petal Wave Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 389,
    tag: "Fresh Drop",
    description: "A boutique scarf with soft movement and enough presence to make personalization feel special.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19 (5).jpeg",
    purchasable: true,
    customizationRequired: false,
  },
  {
    id: 19,
    slug: "mint-haze-scarf",
    name: "Mint Haze Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 359,
    tag: "Lightweight",
    description: "A soft-toned scarf meant for easy layering, event gifting, and optional custom wording.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19 (6).jpeg",
    purchasable: true,
    customizationRequired: false,
  },
  {
    id: 20,
    slug: "pearl-drift-scarf",
    name: "Pearl Drift Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 419,
    tag: "Pastel Edit",
    description: "A polished scarf piece imagined for elegant gifting and soft, feminine everyday looks.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19 (7).jpeg",
    purchasable: true,
    customizationRequired: false,
  },
  {
    id: 21,
    slug: "sky-veil-scarf",
    name: "Sky Veil Scarf",
    category: "scarf",
    categoryLabel: "Custom Scarf",
    price: 439,
    tag: "Everyday Luxe",
    description: "A versatile custom scarf line for keepsake gifting, event sets, and boutique wardrobe accents.",
    image: "./assets/scarves/WhatsApp Image 2026-04-04 at 17.44.19 (8).jpeg",
    purchasable: true,
    customizationRequired: false,
  },
];
